force-app/main/default/objects/Product2/fields/Is_a_Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_a_Main_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for product filter</description>
    <label>Pay Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Used_For__c.field-meta.xml
<CustomField>
    <fullName>Product_Used_For__c</fullName>
    <description>used for filtering</description>
    <label>Product Used For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gplvs_Main_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/gplvs_Main_Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any</fullName>
    </customValue>
    <customValue>
        <fullName>Block</fullName>
    </customValue>
    <customValue>
        <fullName>Bollards</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Apron</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Curb</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Footings</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Foundation</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Sidewalk</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Slab</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Stairs</fullName>
    </customValue>
    <customValue>
        <fullName>Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Excavation</fullName>
    </customValue>
    <customValue>
        <fullName>Grading</fullName>
    </customValue>
    <customValue>
        <fullName>Interior Slab Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Retaining Wall</fullName>
    </customValue>
    <masterLabel>Main Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LWCqgsProductUsedForController.cls
public with sharing class LWCqgsProductUsedForController {
    @AuraEnabled(cacheable=true)
    public static list<Product2> retrieveProductsUsedFor(String puf) {
        List<Product2> products;
        try{
            products = [SELECT Id, Name FROM Product2 WHERE Is_a_Main_Product__c = true AND Product_Used_For__c includes (:puf) WITH SECURITY_ENFORCED];
        } catch(System.QueryException qe){
            System.debug(qe.getMessage());
        }
        return products;
    }
}