force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Sales_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sales_Direction__c</fullName>
    <label>Sales Direction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Description__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Description__c</fullName>
    <description>Description for this group.</description>
    <inlineHelpText>Description for this group.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Sort order of this group within its quote.</description>
    <inlineHelpText>Sort order of this group within its quote. Start with multiples of 10. ie: 10, 20, 30. This makes it easier to change the ordering. ie: moving first one to second: 20, 25, 30</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LWCqgsQuoteGroupController.cls
public with sharing class LWCqgsQuoteGroupController {
    @AuraEnabled(cacheable=true)
    public static list<SBQQ__QuoteLineGroup__c> retrieveQLGs(String quoteId) {
        List<SBQQ__QuoteLineGroup__c> qlgs;
        try{
            qlgs = [SELECT Id, Name, SBQQ__Description__c, Sales_Direction__c, SBQQ__Number__c FROM SBQQ__QuoteLineGroup__c WHERE SBQQ__Quote__c = :quoteId WITH SECURITY_ENFORCED ORDER BY SBQQ__Number__c ASC];
        } catch(System.QueryException qe){
            System.debug(qe.getMessage());
        }
        return qlgs;
    }

}