force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/Sales_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sales_Direction__c</fullName>
    <label>Sales Direction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__CustomerTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__CustomerTotal__c</fullName>
    <description>Total for this group&apos;s line items before any partner discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items before any partner discounts are applied.</inlineHelpText>
    <label>Customer Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Description__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Description__c</fullName>
    <description>Description for this group.</description>
    <inlineHelpText>Description for this group.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__ListTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListTotal__c</fullName>
    <description>Total for this group&apos;s line items before any discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items before any discounts are applied.</inlineHelpText>
    <label>List Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__NetTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetTotal__c</fullName>
    <description>Total for this group&apos;s line items after all discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items after all discounts are applied.</inlineHelpText>
    <label>Net Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Sort order of this group within its quote.</description>
    <inlineHelpText>Sort order of this group within its quote. Start with multiples of 10. ie: 10, 20, 30. This makes it easier to change the ordering. ie: moving first one to second: 20, 25, 30</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LWCqgsQuoteGroupControllerTest.cls
@isTest
class LWCqgsQuoteGroupControllerTest {
    static testMethod void testQGL (){
        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;

        SBQQ__QuoteLineGroup__c qlg = new SBQQ__QuoteLineGroup__c(Name = 'test', SBQQ__Quote__c = quote.id, SBQQ__Number__c = 1, SBQQ__ListTotal__c = 0, SBQQ__NetTotal__c = 0, SBQQ__CustomerTotal__c = 0);
        insert qlg;

        List<SBQQ__QuoteLineGroup__c> qlgs = LWCqgsQuoteGroupController.retrieveQLGs(quote.id);
            

        System.assert( qlgs  != null);
        /* SBQQ__QuoteLineGroup__c testqlg = [SELECT Id, Name, SBQQ__Description__c, Sales_Direction__c, SBQQ__Number__c, SBQQ__Quote__c FROM SBQQ__QuoteLineGroup__c WHERE SBQQ__Quote__c = :quote.id LIMIT 1];
        System.assertEquals ( testqlg.SBQQ__Quote__c , quote.id); */

    }
}

//https://developer.salesforce.com/forums/?id=9060G000000BfgoQAC