force-app/main/default/objects/Krow__Project_Resources__c/Krow__Project_Resources__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow__Project_Resources__c/fields/Krow__User__c.field-meta.xml
<CustomField>
    <fullName>Krow__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Project_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/Krow__Task__c.object-meta.xml
<CustomObject>
    <label>Klient Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Klient Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow__Task__c/fields/Due_Date_Status__c.field-meta.xml
<CustomField>
    <fullName>Due_Date_Status__c</fullName>
    <description>Used in apex class queryAssignedTasks</description>
    <formula>IF(
  Is_a_Parent_Task__c,
  &quot;&quot;,
  IF(
    Krow__Due_Date__c &lt; TODAY(),
    &quot;OVERDUE&quot;,
    IF(
      AND(
        Krow__Start_Date__c &lt;= TODAY(),
        Krow__Due_Date__c &gt;= TODAY()
      ),
      &quot;CURRENT&quot;,
      IF(
        OR(
          Krow__Start_Date__c &lt;= TODAY() + 7,
          Krow__Due_Date__c &lt;= TODAY() + 7
        ),
        &quot;UPCOMING WEEK&quot;,
        &quot;LATER&quot;
      )
    )
  )
)</formula>
    <label>Due Date Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Is_a_Parent_Task__c.field-meta.xml
<CustomField>
    <fullName>Is_a_Parent_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is a Parent Task</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Krow__Status__c.field-meta.xml
<CustomField>
    <fullName>Krow__Status__c</fullName>
    <description>The status of this task as entered or selected.</description>
    <inlineHelpText>The status of this task as entered or selected.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Krow__Task_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Krow__Task_Due_Date__c</fullName>
    <description>A calculated date/time field representing the Task Due Date.</description>
    <inlineHelpText>A calculated date/time field representing the Task Due Date.</inlineHelpText>
    <label>Task Due Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Krow__Task_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Krow__Task_Start_Date__c</fullName>
    <description>A calculated date/time field representing the Task Start Date.</description>
    <inlineHelpText>A calculated date/time field representing the Task Start Date.</inlineHelpText>
    <label>Task Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Krow__Template_Project__c.field-meta.xml
<CustomField>
    <fullName>Krow__Template_Project__c</fullName>
    <formula>OR(Krow__Project__r.Krow__Project_Template__c, Krow__Project__r.Krow__Public_Project_Template__c , Krow__Project__r.Krow__Task_Template__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Template Project</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Krow__Task__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>used to filter display to assignees</inlineHelpText>
    <label>Live</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Krow__Task_Assignment__c/Krow__Task_Assignment__c.object-meta.xml
<CustomObject>
    <label>Task Assignment</label>
    <nameField>
        <displayFormat>TA-{0000}</displayFormat>
        <label>Task Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Krow__Task_Assignment__c/fields/Krow__Krow_Task__c.field-meta.xml
<CustomField>
    <fullName>Krow__Krow_Task__c</fullName>
    <label>Klient Task</label>
    <referenceTo>Krow__Task__c</referenceTo>
    <relationshipLabel>Task Assignments</relationshipLabel>
    <relationshipName>Task_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Krow__Task_Assignment__c/fields/Krow__Project_Resource__c.field-meta.xml
<CustomField>
    <fullName>Krow__Project_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Resource</label>
    <referenceTo>Krow__Project_Resources__c</referenceTo>
    <relationshipLabel>Task Assignments</relationshipLabel>
    <relationshipName>Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Krow__Task_Assignment__c/fields/Krow__Status__c.field-meta.xml
<CustomField>
    <fullName>Krow__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
                <default>true</default>
                <label>Booked</label>
            </value>
            <value>
                <fullName>Soft Booked</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Krow__Task_Assignment__c/fields/Krow__User__c.field-meta.xml
<CustomField>
    <fullName>Krow__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Task_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/queryAssignedTasks.cls
global with sharing class queryAssignedTasks {
    
    @InvocableMethod(Label = 'Get Assigned Tasks')
    public static List<List<Krow__Task__c>> GetTasks (List<methodInputs> requests)
       {
           	String Due_Date_Status = requests[0].Due_Date_Status;
            
           	//created to hold return list of lists
    		List<List<Krow__Task__c>> wrapper = new List<List<Krow__Task__c>>();
           	//this operates off the current User
            Id userId = UserInfo.getUserId();       
            List<Krow__Project_Resources__c> projResourceId = [select Id from Krow__Project_Resources__c where Krow__User__c = :userid LIMIT 1];
           
           	Set<Id> setids = new Set<Id>();
            for(Krow__Task_Assignment__c t : [select Krow__Krow_Task__r.Id from Krow__Task_Assignment__c where Krow__Project_Resource__r.Id = :projResourceId]){
                setids.add(t.Krow__Krow_Task__r.Id);
            } 
           
           
			// without an ID, simply specify the object to then derive the sobject type
			DescribeSObjectResult describeResult = Krow__Task__c.getSObjectType().getDescribe();

			List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
           
           	String query =
              	' SELECT ' +
                String.join( fieldNames, ',' ) +
              	' FROM ' +
          		describeResult.getName() +
              	' WHERE IsDeleted != TRUE AND Krow__Status__c != \'Completed\' AND Krow__Status__c != \'Archived\''  +
              	' AND Krow__Template_Project__c != TRUE AND Due_Date_Status__c =:Due_Date_Status AND Live__c = TRUE AND Is_a_Parent_Task__c = FALSE AND' +
				' Id IN :setids' +
               	' ORDER BY Krow__Task_Due_Date__c ASC, Krow__Task_Start_Date__c ASC' ;
 

           
			List<Krow__Task__c> assignedTasks = Database.query( query );
			List<Krow__Task__c> responseList=new List<Krow__Task__c>();
           	
           	for (Krow__Task__c assignedTask: assignedTasks ){       
        		responseList.add(assignedTask);     
    		}
			wrapper.add(responseList);
    		return wrapper;
           
       }
    	//input details that comes to apex from flow
    	public class methodInputs{
        	@InvocableVariable(label='Due Date Status' description='OVERDUE | CURRENT | UPCOMING WEEK | LATER' required=true)
        	public String Due_Date_Status;
    	}
}