force-app/main/default/objects/Concrete_Order__c/Concrete_Order__c.object-meta.xml
<CustomObject>
    <label>Concrete Order</label>
    <nameField>
        <displayFormat>CONCRETEORDER-{000000}</displayFormat>
        <label>Concrete Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concrete Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Concrete_Order__c/fields/Actual_Yardage_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Actual_Yardage_Ordered__c</fullName>
    <label>Yardage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/DOW__c.field-meta.xml
<CustomField>
    <fullName>DOW__c</fullName>
    <formula>CASE(WEEKDAY(Requested_Date__c), 
1,&quot;Sunday&quot;, 
2,&quot;Monday&quot;, 
3,&quot;Tuesday&quot;, 
4,&quot;Wednesday&quot;, 
5,&quot;Thursday&quot;, 
6,&quot;Friday&quot;, 
7,&quot;Saturday&quot;, 
&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Day</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Concrete Orders</relationshipLabel>
    <relationshipName>Concrete_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Ordered__c.field-meta.xml
<CustomField>
    <fullName>Ordered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ordered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Released__c.field-meta.xml
<CustomField>
    <fullName>Released__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Released</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Date__c</fullName>
    <label>Requested Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Concrete_Order__c/fields/What_are_we_pouring__c.field-meta.xml
<CustomField>
    <fullName>What_are_we_pouring__c</fullName>
    <label>What are we pouring</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>Used as a junction from opportunity to everything else for users without access to opportunity.</description>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Time.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AM  06:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  06:30</fullName>
    </customValue>
    <customValue>
        <fullName>AM  07:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  07:30</fullName>
    </customValue>
    <customValue>
        <fullName>AM  08:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  08:30</fullName>
    </customValue>
    <customValue>
        <fullName>AM  09:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  09:30</fullName>
    </customValue>
    <customValue>
        <fullName>AM  10:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  10:30</fullName>
    </customValue>
    <customValue>
        <fullName>AM  11:00</fullName>
    </customValue>
    <customValue>
        <fullName>AM  11:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 12:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 12:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 01:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 01:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 02:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 02:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 03:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 03:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 04:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 04:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 05:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 05:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 06:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 06:30</fullName>
    </customValue>
    <customValue>
        <fullName>PM 07:00</fullName>
    </customValue>
    <customValue>
        <fullName>PM 07:30</fullName>
    </customValue>
    <masterLabel>Time</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConcreteOrderController.cls
public with sharing class ConcreteOrderController {

    // PassCode Validation for Visual Force concreteorder.page
    // values from visualforce page
    public String inputPassCode{get;set;} 
    public Boolean authenticated{get;set;}

    public PageReference validatePassCode(){
        authenticated = inputPassCode == 'thundernj.concrete';
        return null;
    }

    //Called from LWC concrtoUpcomDelivList
    @AuraEnabled(cacheable=true)
    public static List<Concrete_Order__c> retrieveConcreteOrders(String jobId) {
        List<Concrete_Order__c> concreteOrders;
        try{
            concreteOrders = [SELECT Id, Job__r.Name, Job__r.Id, What_are_we_pouring__c, Actual_Yardage_Ordered__c, Notes__c, Requested_Date__c, Time__c, Ordered__c, Released__c, DOW__c FROM Concrete_Order__c WHERE IsDeleted = false AND Requested_Date__c > YESTERDAY ORDER BY Requested_Date__c ASC, Time__c ASC];
        } catch(System.QueryException qe){
            System.debug(qe.getMessage());
        }
        return concreteOrders;
    }

    
}