force-app/main/default/objects/Pay_Item__c/Pay_Item__c.object-meta.xml
<CustomObject>
    <description>Used by Salesman to instruct Estimator how to organize the quote</description>
    <label>Pay Item</label>
    <nameField>
        <displayFormat>Pay_Item-{00000000}</displayFormat>
        <label>Pay Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pay_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_a_Main_Product__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pay Items from Sales</relationshipLabel>
    <relationshipName>Pay_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pay_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Pay Items from Sales</relationshipLabel>
    <relationshipName>Pay_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pay_Item__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SBQQ__QuoteLineGroup__c.SBQQ__Quote__c</field>
            <operation>equals</operation>
            <valueField>$Source.Quote__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Pay Items from Sales</relationshipLabel>
    <relationshipName>Pay_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_a_Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Is_a_Main_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for product filter</description>
    <label>Pay Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Used_For__c.field-meta.xml
<CustomField>
    <fullName>Product_Used_For__c</fullName>
    <description>used for filtering</description>
    <label>Product Used For</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>gplvs_Main_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__CustomerTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__CustomerTotal__c</fullName>
    <description>Total for this group&apos;s line items before any partner discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items before any partner discounts are applied.</inlineHelpText>
    <label>Customer Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__ListTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListTotal__c</fullName>
    <description>Total for this group&apos;s line items before any discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items before any discounts are applied.</inlineHelpText>
    <label>List Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__NetTotal__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetTotal__c</fullName>
    <description>Total for this group&apos;s line items after all discounts are applied.</description>
    <inlineHelpText>Total for this group&apos;s line items after all discounts are applied.</inlineHelpText>
    <label>Net Total</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/fields/SBQQ__Number__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Number__c</fullName>
    <description>Sort order of this group within its quote.</description>
    <inlineHelpText>Sort order of this group within its quote. Start with multiples of 10. ie: 10, 20, 30. This makes it easier to change the ordering. ie: moving first one to second: 20, 25, 30</inlineHelpText>
    <label>Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/gplvs_Main_Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Any</fullName>
    </customValue>
    <customValue>
        <fullName>Block</fullName>
    </customValue>
    <customValue>
        <fullName>Bollards</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Apron</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Curb</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Footings</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Foundation</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Sidewalk</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Slab</fullName>
    </customValue>
    <customValue>
        <fullName>Concrete Stairs</fullName>
    </customValue>
    <customValue>
        <fullName>Demolition</fullName>
    </customValue>
    <customValue>
        <fullName>Excavation</fullName>
    </customValue>
    <customValue>
        <fullName>Grading</fullName>
    </customValue>
    <customValue>
        <fullName>Interior Slab Trenching</fullName>
    </customValue>
    <customValue>
        <fullName>Retaining Wall</fullName>
    </customValue>
    <masterLabel>Main Services</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LWCqgsPayItemControllerTest.cls
@isTest
class LWCqgsPayItemControllerTest {
    static testMethod void testPI (){
        Product2 product = new Product2(
            Name = 'test',
            Product_Used_For__c = 'Block',
            Is_a_Main_Product__c = true
        );
        insert product;

        SBQQ__Quote__c quote = new SBQQ__Quote__c();
        insert quote;

        SBQQ__QuoteLineGroup__c qlg = new SBQQ__QuoteLineGroup__c(
            Name = 'test', 
            SBQQ__Quote__c = quote.id, 
            SBQQ__Number__c = 1, 
            SBQQ__ListTotal__c = 0, 
            SBQQ__NetTotal__c = 0, 
            SBQQ__CustomerTotal__c = 0
        );
        insert qlg;

        Pay_Item__c payitem = new Pay_Item__c(
            Product__c = product.id,
            Quote__c = quote.id,
            Quote_Line_Group__c = qlg.id
        );
        insert payitem;

        List<Pay_Item__c> payitems = LWCqgsPayItemController.retrievePayItems(qlg.id);
        System.assert( payitems  != null);
    }
}