force-app/main/default/objects/Pay_Item__c/Pay_Item__c.object-meta.xml
<CustomObject>
    <description>Used by Salesman to instruct Estimator how to organize the quote</description>
    <label>Pay Item</label>
    <nameField>
        <displayFormat>Pay_Item-{00000000}</displayFormat>
        <label>Pay Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pay Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pay_Item__c/fields/Instructions_Info__c.field-meta.xml
<CustomField>
    <fullName>Instructions_Info__c</fullName>
    <label>Instructions/Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pay_Item__c/fields/Order_in_Group__c.field-meta.xml
<CustomField>
    <fullName>Order_in_Group__c</fullName>
    <inlineHelpText>Start with 10 and increments of 10 to make inserting between easier</inlineHelpText>
    <label>Order in Group</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pay_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pay Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Is_a_Main_Product__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Pay Items from Sales</relationshipLabel>
    <relationshipName>Pay_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pay_Item__c/fields/Quote_Line_Group__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SBQQ__QuoteLineGroup__c.SBQQ__Quote__c</field>
            <operation>equals</operation>
            <valueField>$Source.Quote__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SBQQ__QuoteLineGroup__c</referenceTo>
    <relationshipLabel>Pay Items from Sales</relationshipLabel>
    <relationshipName>Pay_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLineGroup__c/SBQQ__QuoteLineGroup__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineGroupHelp</customHelpPage>
    <description>Group of line items on a quote.</description>
    <label>Quote Line Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LWCqgsPayItemController.cls
public with sharing class LWCqgsPayItemController {
    @AuraEnabled(cacheable=true)
    public static List<Pay_Item__c> retrievePayItems(String qlgId) {
        List<Pay_Item__c> payItems;
        try{
            payItems = [SELECT Id, Product__r.Name, Instructions_Info__c, Order_in_Group__c, Quote_Line_Group__r.Id FROM Pay_Item__c WHERE Quote_Line_Group__c = :qlgId WITH SECURITY_ENFORCED ORDER BY Order_in_Group__c ASC];
        } catch(System.QueryException qe){
            System.debug(qe.getMessage());
        }
        return payItems;
    }
}